export const API_KEYS = {
  NEWS_API_KEY: process.env.REACT_APP_NEWS_API_KEY || "",
  GUARDIAN_API_KEY: process.env.REACT_APP_GUARDIAN_API_KEY || "",
  NEW_YORK_API_KEY: process.env.REACT_APP_NEW_YORK_API_KEY || "",
};

export const API_BASE_URLS = {
  NEWS_API_BASE_URL: process.env.REACT_APP_NEWS_API_BASE_URL || "",
  GUARDIAN_API_BASE_URL: process.env.REACT_APP_GUARDIAN_API_BASE_URL || "",
  NEW_YORK_API_BASE_URL: process.env.REACT_APP_NEW_YORK_API_BASE_URL || "",
};
